PR to merge capstone with main
AliRezaBmeDu/conference-capstone pull request #1
Opened 2023-07-06 20:59 UTC by AliRezaBmeDu

In this branch, I have done the following changes:

- Create two different page(homepage and about page) for an upcoming summit.
- Add responsiveness to the pages.
- Add multiple sections with multiple features for desktop as well as mobile version.
- Add functionality of the buttons through javascript.
- Create a whole section of a page dynamically using javascript.
- Add necessary designs.
- Resolve the linters for html-css-js

2023-07-06 22:23 UTC, usorfaitheloho requested changes
> Hi @AliRezaBmeDu  ,
> 
> Great job for implementing some of the Project Requirement, but there are some changes that need to be implemented in order to proceed to the next project 👍
> 
> ## Highlights 👏🏻
> ✔️ No linters error ✔️ You used correct Git Hub-Flow. ✔️ Good README ✔️ Good Commit Messages
> 
> ![almost](https://user-images.githubusercontent.com/65860678/170491251-b1add8ba-b18f-4648-a893-20e510d957fd.gif) 

> ## Required Changes ♻️
> _Check the comments below the review._
> 
> * [ ]  Kindly I recommend you use the design color given in the design as it is part of the instructions to replicate the color in the deign given.

![image](https://github.com/AliRezaBmeDu/conference-capstone/assets/20537712/f298a0d6-1bde-474a-abcc-47f8749fd5a4)

> 
> ## Optional suggestions
> _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
> 
> Cheers and Happy coding!👏👏👏
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
> 
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> 
> _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-06 22:23 UTC, usorfaitheloho commented on index.html
> +        </nav>
Kindly use a `header` tag for the section containing the logo and `nav` items as a good semantics principle of HTML 😄

2023-07-06 22:23 UTC, usorfaitheloho commented on index.html
> +                <h1>Main Program</h1>
- Please note that your webpage is to have only one H1 tag for search engine optimization and your hx tags should follow the hierarchy principle which is h1 before h2, h2 before h3, h3 before h4 etc to show good semantics and code organisation
- please also add the horizontal line after the `Main Program`headign as it is in the design

2023-07-06 22:23 UTC, usorfaitheloho commented on index.html
> +    </div>
Kindly remember that yourd esign is to obey the color and fonts guidelines, please for the whole of your project, change the colors to suit the design you were given. Also for the nav section, kindly alighn the the two navs to be on the same alignment and position as the design given 

Design given :

![image](https://github.com/AliRezaBmeDu/conference-capstone/assets/20537712/2adab618-6caf-465f-b3d1-641a3b34ba85)

Your design :
![image](https://github.com/AliRezaBmeDu/conference-capstone/assets/20537712/56c3e3e3-8791-4fd9-8b2e-263dd4e1958a)

2023-07-06 22:23 UTC, usorfaitheloho commented on index.html
> +
Please change the color of your design, as you used a different color from the color guideline given in our design

2023-07-06 22:23 UTC, usorfaitheloho commented on index.html
> +    </div>
Kindly take note of the color contrast in all sections of your project and the design you were given, so that it matches the required design. Also please work on the `See the Whole Program` design of your project

Design given :
![image](https://github.com/AliRezaBmeDu/conference-capstone/assets/20537712/6c397658-8284-4373-9b5c-e4afbe929579)

Your design :
![image](https://github.com/AliRezaBmeDu/conference-capstone/assets/20537712/f678dcc1-ff0c-4f3f-b32f-71fdfa02eec9)

2023-07-06 22:23 UTC, usorfaitheloho commented on index.html
> +
Kindly implement the speakers section design so it looks similar to what we have in the design given, by adding the necessary background image, horizontal line, font color and font size for this section 😄 

Your design :
![image](https://github.com/AliRezaBmeDu/conference-capstone/assets/20537712/f1fedd4a-21a6-4a77-abd2-da35a6c58a7e)

Design given :
![image](https://github.com/AliRezaBmeDu/conference-capstone/assets/20537712/4298ca02-9e37-42f9-bf30-40d8ce430dc6)

2023-07-06 22:23 UTC, usorfaitheloho commented on index.html
> +        <h1>Partners</h1>
Kindly add a horizontal line here as it is in the design , and use another hx tag ensuring you following the hieracy order principle I stated previously

2023-07-06 22:23 UTC, usorfaitheloho commented on index.html
> +</footer>
Kinldy fix the footer positioning design for both your about and home page as it should be centered and not aligned to the right. Please follow the design template given 

Your design :
![image](https://github.com/AliRezaBmeDu/conference-capstone/assets/20537712/bee2e3db-7629-4944-b691-9ee71541c9b0)

Figma design :
![image](https://github.com/AliRezaBmeDu/conference-capstone/assets/20537712/c9ab927d-5026-4183-885c-4c8a448950a8)

2023-07-06 22:23 UTC, usorfaitheloho commented on index.html
> +</html>
Kindly implement the following changes for the mobile view of your homepage :

1.  for your mobile menu, kindly fix the position issue as the background color doesn't extend to the end, fix the margin as the items are to be centered and also use the color guideline for the project here 😄 
![image](https://github.com/AliRezaBmeDu/conference-capstone/assets/20537712/3390f644-32d9-4a72-ba0d-f19d795248b6)

3. Kindly add this button in your mobile version 

![image](https://github.com/AliRezaBmeDu/conference-capstone/assets/20537712/fb7c0b99-0c21-4db1-94f9-8fd8595f086c)

3. Please implement the speakers section to be similar to the design given

Your design :
![image](https://github.com/AliRezaBmeDu/conference-capstone/assets/20537712/08f684fa-6a44-44fc-afda-de6435c7f2ad)

Design given :
![image](https://github.com/AliRezaBmeDu/conference-capstone/assets/20537712/b1e84d3b-c6ce-463c-acf5-9018debf3455)

2023-07-06 22:23 UTC, usorfaitheloho commented on about.html
> +
Kindly fix the header for this section as it is too big, add the horizontal line, and add the background color design for this and other sections of your project 👍 

Design given : 

![image](https://github.com/AliRezaBmeDu/conference-capstone/assets/20537712/2d5fccaa-9c82-4c6d-9d6c-afbbb8402bfc)

Your design :
![image](https://github.com/AliRezaBmeDu/conference-capstone/assets/20537712/7b34d474-64f2-4424-9f66-310c0b4093e3)

2023-07-06 22:23 UTC, usorfaitheloho commented on about.html
> +</html>
For the mobile view, kindly implement these design changes :

- Please adjust the position of the mobile menu to the leftmost side of your view, just as it in the design. Please do this for the home page as well 👍 
- Kindly fix this section as it have too much margin and should be similar to our design given, also remember to add the design background color used
Your design :
![image](https://github.com/AliRezaBmeDu/conference-capstone/assets/20537712/02e765ae-33cf-46e1-bb49-2adc7655eeb5)

Design given :
![image](https://github.com/AliRezaBmeDu/conference-capstone/assets/20537712/0e76c436-93d8-4cbc-9bd4-d457078fa01f)

- Please add a horizontal line to the `partners`title similar to the dsign
- Kindly reduce the font size of the footer so it has similarity with the design given 
-
Your design :
![image](https://github.com/AliRezaBmeDu/conference-capstone/assets/20537712/c7b49ed7-f37f-4b4b-b617-a277d585c04b)

Design given :
![image](https://github.com/AliRezaBmeDu/conference-capstone/assets/20537712/f69e6c4a-d539-45d7-8fc8-cdf72e1fc2c4)

2023-07-07 18:53 UTC, KayLemba approved these changes
# STATUS: APPROVED :green_circle: :clap: 

Hello @AliRezaBmeDu       , 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit:  
Congratulations! 🎉  Keep up the good work 🥂 

HIGHLIGHTS:

- [x]  Professional README
- [x] No linter errors
- [x] Descriptive P.R
- [x] Nice and Neat UI design  🥇 🥂 
 



 
 

 










 








Now you can merge this branch and move on :1st_place_medal: 
Happy Coding cheers 🥇 💯 



![well-1](https://user-images.githubusercontent.com/64173189/128382030-38e7de91-f6f2-45cf-b54e-8068e0446e4c.gif)

Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.



Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._]]

2023-07-08 04:42 UTC, merged